### PR TITLE
Flutter Resources Added

### PR DESCRIPTION
**Pull request by as3hr**
## 🚀 What does this PR do?

I have created three folders and it's all about Flutter, so one is for documentation, one for tutorials and resources, and the last one for the roadmap.
All the folders have 1 or 2 text files that have links to the roadmap or tutorials.
I have tried to make it simple and to the point.

  

## 🎯 Purpose:

The links will then lead you to roadmaps, the documentation page, and the code lab.
All these are the main resources that a person will need to learn flutter

## 🔗 Related PRs and Issues

Not any.

  
  
  

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project/documentation.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a student at DHA Suffa University.
- [ ] I am a MLSC-DSU Core-Team Member.

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
@as3hr Kindly provide details about the changes in your PR.

**Comment by as3hr** [comment]
I have created three folders and it's all about Flutter, so one is for documentation, one for tutorials and resources, and the last one for the roadmap.
All the folders have 1 or 2 text files that have links to the roadmap or tutorials.
I have tried to make it simple and to the point.

**Comment by as3hr** [comment]
The links will then lead you to roadmaps, the documentation page, and the code lab.
All these are the main resources that a person will need to learn flutter

**Comment by KiranAminPanjwani** [comment]
> ## 🚀 What does this PR do?
> I have created three folders and it's all about Flutter, so one is for documentation, one for tutorials and resources, and the last one for the roadmap. All the folders have 1 or 2 text files that have links to the roadmap or tutorials. I have tried to make it simple and to the point.
> 
> ## 🎯 Purpose:
> The links will then lead you to roadmaps, the documentation page, and the code lab. All these are the main resources that a person will need to learn flutter
> 
> ## 🔗 Related PRs and Issues
> Not any.
> 
> ## ✔️ Check List (Check all the applicable boxes)
> * [ ]  My code follows the code style of this project/documentation.
> * [ ]  This PR does not contain plagiarized content.
> * [ ]  The title of my pull request is a short description of the requested changes.
> * [ ]  I am a student at DHA Suffa University.
> * [ ]  I am a MLSC-DSU Core-Team Member.

I have updated your comment by adding your responses to it. Kindly check the boxes that apply. 

It would be really helpful if you could include your details in the comment while creating a PR. This makes it easier for everyone involved in the project to understand your contributions and provide feedback. Don't worry if you forget, it happens to everyone! Just remember to try your best to include your details next time. Keep up the great work!

**Comment by KiranAminPanjwani** [comment]
It looks good to me. Thank you for contributing.😊

**Pull request merged**
