### PR TITLE
Added Ashar to Contributors 2023 List.md

### PR DESCRIPTION
**Pull request by as3hr**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project/documentation.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a student at DHA Suffa University.
- [ ] I am a MLSC-DSU Core-Team Member.

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
@as3hr Kindly rename your PR title to "Added [your name] to [File name]".

**Comment by as3hr** [comment]
I didn't understand what do you mean by the filename

> @as3hr Kindly rename your PR title to "Added [your name] to [File name]". Also, either provide details in the comment or erase all the text.

I didn't understand, what do you mean by filename

**Comment by KiranAminPanjwani** [comment]
Mention the name of the file in which you are making modifications. In your case, the file name is "Contributors 2023 List.md".

**Comment by KiranAminPanjwani** [comment]
> I didn't understand what do you mean by the filename
> 
> > @as3hr Kindly rename your PR title to "Added [your name] to [File name]". Also, either provide details in the comment or erase all the text.
> 
> I didn't understand, what do you mean by filename

Mention the name of the file in which you are making modifications. In your case, the file name is "Contributors 2023 List.md".

**Comment by KiranAminPanjwani** [comment]
@as3hr Kindly add your name in the last row.

**Pull request closed without merging**
